### PR TITLE
fix: use correct URL to prevent crashing the app

### PR DESCRIPTION
**Pull request by j-m-hoffmann**

### CODE REVIEW

**Comment by j-m-hoffmann** [comment]
@googlebot I signed it!

**Comment by jtavva** [comment]
This is fixed now, thank you for your contribution.

**Comment by jtavva** [comment]
This is fixed now, thank you for your contribution.

**Comment by jtavva** [comment]
This issue is fixed now in the following update: 
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/commit/df30c589f056ec1cd4247253a35fe72b4f50bf40

**Pull request closed without merging**
